CREATE TABLE public.origem_admin_roles (user_id uuid PRIMARY KEY, role text NOT NULL CHECK (role = 'admin'), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.origem_admin_roles TO authenticated;
GRANT ALL ON public.origem_admin_roles TO service_role;
ALTER TABLE public.origem_admin_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own admin role" ON public.origem_admin_roles FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE FUNCTION public.origem_is_admin() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS (SELECT 1 FROM public.origem_admin_roles WHERE user_id = auth.uid() AND role = 'admin') $$;
REVOKE ALL ON FUNCTION public.origem_is_admin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.origem_is_admin() TO authenticated;
CREATE TABLE public.origem_companies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 200), contact text, blocked boolean NOT NULL DEFAULT false, expires_at timestamptz NOT NULL, code_hash text UNIQUE, last_access_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT ALL ON public.origem_companies TO service_role;
ALTER TABLE public.origem_companies ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.origem_sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.origem_companies(id) ON DELETE CASCADE, token_hash text NOT NULL UNIQUE, expires_at timestamptz NOT NULL, revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT ALL ON public.origem_sessions TO service_role;
ALTER TABLE public.origem_sessions ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.origem_data (company_id uuid PRIMARY KEY REFERENCES public.origem_companies(id) ON DELETE CASCADE, payload jsonb NOT NULL DEFAULT '{}'::jsonb, version bigint NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT ALL ON public.origem_data TO service_role;
ALTER TABLE public.origem_data ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.origem_invoices (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.origem_companies(id) ON DELETE CASCADE, amount_cents integer NOT NULL CHECK (amount_cents > 0), due_on date NOT NULL, status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','paid','cancelled')), notes text, paid_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT ALL ON public.origem_invoices TO service_role;
ALTER TABLE public.origem_invoices ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.origem_audit (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, company_id uuid REFERENCES public.origem_companies(id) ON DELETE SET NULL, actor text NOT NULL, action text NOT NULL, detail text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT ALL ON public.origem_audit TO service_role;
ALTER TABLE public.origem_audit ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.origem_attempts (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, ip_hash text NOT NULL, succeeded boolean NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT ALL ON public.origem_attempts TO service_role;
ALTER TABLE public.origem_attempts ENABLE ROW LEVEL SECURITY;
CREATE FUNCTION public.origem_touch() RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END $$;
CREATE TRIGGER touch_origem_admin_roles BEFORE UPDATE ON public.origem_admin_roles FOR EACH ROW EXECUTE FUNCTION public.origem_touch();
CREATE TRIGGER touch_origem_companies BEFORE UPDATE ON public.origem_companies FOR EACH ROW EXECUTE FUNCTION public.origem_touch();
CREATE TRIGGER touch_origem_sessions BEFORE UPDATE ON public.origem_sessions FOR EACH ROW EXECUTE FUNCTION public.origem_touch();
CREATE TRIGGER touch_origem_data BEFORE UPDATE ON public.origem_data FOR EACH ROW EXECUTE FUNCTION public.origem_touch();
CREATE TRIGGER touch_origem_invoices BEFORE UPDATE ON public.origem_invoices FOR EACH ROW EXECUTE FUNCTION public.origem_touch();
CREATE TRIGGER touch_origem_audit BEFORE UPDATE ON public.origem_audit FOR EACH ROW EXECUTE FUNCTION public.origem_touch();
CREATE TRIGGER touch_origem_attempts BEFORE UPDATE ON public.origem_attempts FOR EACH ROW EXECUTE FUNCTION public.origem_touch();
CREATE INDEX origem_attempts_limit ON public.origem_attempts (ip_hash, created_at DESC);
CREATE INDEX origem_sessions_company ON public.origem_sessions (company_id);
CREATE INDEX origem_audit_created ON public.origem_audit (created_at DESC);
CREATE INDEX origem_invoices_company ON public.origem_invoices (company_id);